# Use an official Python runtime as a parent image
FROM python:3.12.0-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install Flask
RUN pip install Flask flask-cors

# Copy the content of the local src directory to the working directory
COPY . .

# Make port 7001 available to the world outside this container
EXPOSE 7001

# Define environment variable
ENV NAME World
ENV PYTHONUNBUFFERED=1

# Run apiserver.py when the container launches
CMD ["python", "./apiserver.py"]