# Use an official Python runtime as a parent image
FROM python:3.12.0-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Define environment variable
ENV URL_TO_CLICK="http://webfront/"
ENV RETRY_ON_SUCCESS_INTERVAL=1.0
ENV PYTHONUNBUFFERED=1

# Run clicker.py when the container launches
CMD ["python", "./clicker.py"]
