apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: progrium/stress:latest
        resources:
         limits:
           memory: "256M"
           cpu: "500m"
        ports:
        - containerPort: 80
        command: ["/bin/bash", "-c", "sleep 3600"]
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: ubuntu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ubuntu
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
---

